SNAPSHOT_EMPTY_COLLECTION_KEY = "empty snapshot collection"
SNAPSHOT_UNKNOWN_COLLECTION_KEY = "unknown snapshot collection"

EXIT_STATUS_FAIL_UNUSED = 1

SYMBOL_ELLIPSIS = "..."  # U+2026
SYMBOL_NEW_LINE = "␤"  # U+2424
SYMBOL_CARRIAGE = "␍"  # U+240D

DIFF_LINE_COUNT_LIMIT = 100
DIFF_LINE_WIDTH_LIMIT = 1000

DISABLE_COLOR_ENV_VAR = "ANSI_COLORS_DISABLED"
DISABLE_COLOR_ENV_VARS = {DISABLE_COLOR_ENV_VAR, "NO_COLOR"}

PYTEST_NODE_SEP = "::"
TEXT_ENCODING = "utf-8"
