name: setup-env
description: Setup Environment
inputs:
  python-version:
    description: Version of python
    required: true
outputs:
  python-version:
    value: ${{ steps.detect-python.outputs.version }}
    description: Detected Python version.
runs:
  using: "composite"
  steps:
    - name: Detect Python Version
      id: detect-python
      run: |
        if [[ -z "${{ inputs.python-version }}" ]]; then
          echo "version=$(head -n1 .python-version | tr -d '\n')" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.python-version }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Install UV
      id: install-uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Python Project
      shell: bash
      run: |
        uv sync --locked --all-extras --dev
