name: Syrupy Manual Release

on:
  workflow_dispatch:

env:
  CI: 1
  VENV: .venv

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Install project dependencies
        run: . script/bootstrap
      - name: Release
        uses: cycjimmy/semantic-release-action@v3.4.0
        with:
          branch: main
          dry_run: false
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
